# Site wide configuration

title: Lifestyle Design
description: Making Friends and Money
logo: //placehold.it/120x120 # 120x120 px default image used for Twitter summary card
teaser: 495x247.jpg # 400x250 px default teaser image used in image archive grid
locale:
url: http://lifestyledz.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Wacey Pruit
  email: wacey@lifestyledz.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
